<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_views_query_alter().
 */
function drupal_practice_views_query_alter(ViewExecutable $view, QueryPluginBase $query,): void {

//   dump($view);
//   dump($query);

  if ($view->id() !== 'practice_content') {
    return;
  }

  $query->addWhere(
    0,
    'node_field_data.nid',
    17,
    '<>'
  );

}